version: '3'

services:
    graylog:
        image: graylog/graylog:4.0
        environment:
            - GRAYLOG_PASSWORD_SECRET=${GRAYLOG_PASSWORD_SECRET}
            - GRAYLOG_ROOT_PASSWORD_SHA2=${GRAYLOG_ROOT_PASSWORD_SHA2}
            - GRAYLOG_HTTP_EXTERNAL_URI=${GRAYLOG_HTTP_EXTERNAL_URI}
        entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
        restart: always
        depends_on:
            - mongo
            - elasticsearch
        ports:
            - ${GRAYLOG_HTTP_PORT}:9000
            - ${GRAYLOG_SYS_TCP_PORT}:1514
            - ${GRAYLOG_SYS_UDP_PORT}:1514/udp
            - ${GRAYLOG_GELF_TCP_PORT}:12201
            - ${GRAYLOG_GELF_UDP_PORT}:12201/udp
        volumes:
            - ./docker/graylog/storage/graylog/data:/usr/share/graylog/data
            - ./docker/graylog/storage/graylog/plugin:/usr/share/graylog/plugin
            - ./docker/graylog/storage/graylog/config:/usr/share/graylog/data/config
        networks:
            - docker-network

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
        environment:
            - http.host=0.0.0.0
            - transport.host=localhost
            - network.host=0.0.0.0
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        deploy:
            resources:
                limits:
                    memory: 1g
        volumes:
            - ./docker/graylog/storage/elasticsearch/data:/usr/share/elasticsearch/data
        networks:
            - docker-network

    mongo:
        image: mongo:4.2
        volumes:
            - ./docker/graylog/storage/mongo/data:/data/db
        networks:
            - docker-network

networks:
    docker-network:
        name: docker-network
        driver: bridge
